1.

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 0, -1],
              [-0.5, 1, -0.25],
              [1, -0.5, 1]])

In [11]:
n = A.shape[0]

D = np.zeros_like(A)
for i in range(n):
  D[i,i] = A[i,i]

L = np.zeros_like(A)
for i in range(n):
  for j in range(n):
    if i > j:
      L[i,j] = -A[i,j]

U = np.zeros_like(A)
for i in range(n):
  for j in range(n):
    if i < j:
      U[i,j] = -A[i,j]

In [24]:
def spectral_radius(T):
  eigval = np.linalg.eigvals(T)
  rho = np.max(np.abs(eigval))
  return rho

In [18]:
print("{} \n\n {} \n\n {}".format(D, L, U))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

 [[ 0.   0.   0. ]
 [ 0.5  0.   0. ]
 [-1.   0.5  0. ]] 

 [[ 0.   -0.    1.  ]
 [ 0.    0.    0.25]
 [ 0.    0.    0.  ]]


In [9]:
Tj = np.matmul(D, (L+U))
Tj

array([[ 0.  ,  0.  ,  1.  ],
       [ 0.5 ,  0.  ,  0.25],
       [-1.  ,  0.5 ,  0.  ]])

In [25]:
spectral_radius(Tj)

0.9721052103388309

In [22]:
X = np.linalg.inv(D - L)
Tgs = np.matmul(X, U)
Tgs

array([[ 0.   ,  0.   ,  1.   ],
       [ 0.   ,  0.   ,  0.75 ],
       [ 0.   ,  0.   , -0.625]])

In [26]:
spectral_radius(Tgs)

0.625

3.

In [27]:
A = np.array([[2, -1, 1],
              [2, 2, 2],
              [-1, -1, 2]], dtype = np.double)
b = np.array([-1, 4, -5], dtype = np.double)