# Pemrograman dengan Python

Bab ini membahas tentang dasar-dasar pemrograman di Python yang dibutuhkan untuk mengimplementasikan metode-metode numerik. Keperluan akan manipulasi dan visualisasi data juga akan dibahas di bab ini, dimana sebagian besar menggunakan library `numpy` dan `matplotlib`.

## Representasi Vektor dan Matriks

Kita mulai dengan membangun suatu vektor. Vektor secara sederhana adalah sub-bagian dari matriks yang hanya memiliki sebuah kolom atau baris. Misalkan kita diberikan suatu vektor

$$
\vec{x} = 
\begin{bmatrix}
1 & 2 & 3
\end{bmatrix}
$$

maka, untuk merepresentasikannya di Python kita dapat menggunakan konsep `array` di library `numpy` atau disebut __numpy array__. Pertama, kita lakukan `import` library `numpy` dan kemudian deklarasikan suatu variabel yang bernilai numpy array.

In [2]:
import numpy as np

x = np.array([1, 2, 3])
print(x)

[1 2 3]


Untuk mengakses masing-masing elemen pada `x`, dapat dilakukan dengan cara

In [3]:
x[1]

2

In [4]:
A = np.array([[1, 3, 2], [4, 5, 6], [1, 2, 1]])
print(A)

[[1 3 2]
 [4 5 6]
 [1 2 1]]


In [5]:
A[1,2]

6

In [6]:
A[:,1]

array([3, 5, 2])

In [7]:
A[1,:]

array([4, 5, 6])

In [14]:
A[0:2, 1]

array([3, 5])

In [18]:
A[1,0:2]

array([4, 5])

In [24]:
print(A.T)

[[1 4 1]
 [3 5 2]
 [2 6 1]]


In [23]:
C = np.array([1.+2.j, 3, 2])
print(C)
print(C.dtype)

[1.+2.j 3.+0.j 2.+0.j]
complex128
